name: Documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  doc:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build documentation
        run: cargo doc --no-deps

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc/aetherus_events

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4